---
clean:
    check_missing_values: true
    check_duplicate_values: true
    check_invalid_values: false
    check_data_types: false
    fill_missing_values: true
    missing_value_columns: ["water_point:water_source_used"]
    fill_missing_value_with: "no"
    check_out_of_range_values: false
    range_min_value: 1
    range_max_value: 4
    check_max_value: []
    check_min_value: []
transform:
    map_yes_no_to_1_0: true
    columns_to_map: ["water_point:source_functional", "water_point:close_water_source"]
    change_column_to_datetime: []
    change_format: false
    apply_function_to_column: true
    apply_function_to_row: false
    aggregate_data: false
    group_data: false
    sort_data: false
    filter_data: false
email:
    user: "mr.kleffy@gmail.com"
    password: jjzlpafgphtmhfrs
    recipient: ["mr.kleffy@gmail.com", "adebiyi_sina@yahoo.com", "confidencevandu@gmail.com", "faizasani934@gmail.com", "mangutsunday@gmail.com", "biyabobai@gmail.com", "dogodeborah@yahoo.com"] 


# skills@click-onkaduna.ng
# recipient: ["mr.kleffy@gmail.com"]
